name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: CMake workflow
      run: cmake --workflow --preset default

  windows-build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: CMake workflow
      run: cmake --workflow --preset default

  include-what-you-use:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: CMake workflow
      run: cmake --workflow --preset include-what-you-use

